services:

  postgres:
    image: postgres:12
    container_name: helper_bot_psg
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: helper
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data

  python:
    container_name: helper_bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8001
    ports:
      - 8001:8001
    depends_on:
      - postgres

volumes:
  pg_data:
    driver: local